t_mem: 50
t_mem_run: 50
opt_algorithm: 'adam'
n_train_steps: 25
batch_size: 10
eta0: 0.001
output_lambda2: 0.1
layers:
  -
    rnn_type: 'LOWD'
    activation: 'sigmoid'
    n_unit: 10000
    lowd_inner_dim: 5
    lambda2: 0.1
    lambda1: 0.0
