t_mem: 20
t_mem_run: 50
opt_algorithm: 'adam'
n_train_steps: 25
batch_size: 10
eta0: 0.001
layers:
  -
    rnn_type: 'EI'
    width: 2
    height: 1
    num_e: 100
    ei_ratio: 0.75
    lambda1: 0.01
    lambda2: 0.01
    activation: 'relu'
    activity_deg: 2
    activity_lambda: 0
    space_const: 0.350
