t_mem: 20
t_mem_run: 50
opt_algorithm: 'adam'
n_train_steps: 20
batch_size: 10
eta0: 0.01
layers:
  -
    rnn_type: 'SRNN'
    activation: 'tanh'
    n_unit: 5
    lambda2: 0.05
  -
    rnn_type: 'SRNN'
    activation: 'tanh'
    n_unit: 10
    lambda2: 0.05
