t_mem: 50
t_mem_run: 50
opt_algorithm: 'adam'
n_train_steps: 5
batch_size: 10
eta0: 0.001
output_lambda2: 0.1
layers:
  -
    rnn_type: 'SRNN'
    activation: 'tanh'
    n_unit: 100
    lambda2: 0.1
    lambda1: 0.0
