run_dir: 'runs'

data_dir: 'data'
data_file: 'text/war_and_peace.clean'


prediction_signals: []

n_prop: 100
n_reject: 10
n_batch: 100
n_train_steps: 7001 # number of forward prop steps

train_state_reset_rate: 6000 # in input steps

grad_clip_norm: 1.0

opt_algorithm: 'adam'
learning_rate: .004
